// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package egress

import (
	"context"
)

// iteratorForAppendEventBatch implements pgx.CopyFromSource.
type iteratorForAppendEventBatch struct {
	rows                 []AppendEventBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForAppendEventBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAppendEventBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].At,
		r.rows[0].Source,
		r.rows[0].Kind,
		r.rows[0].Severity,
		r.rows[0].Payload,
	}, nil
}

func (r iteratorForAppendEventBatch) Err() error {
	return nil
}

func (q *Queries) AppendEventBatch(ctx context.Context, arg []AppendEventBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"telemetry_event"}, []string{"at", "source", "kind", "severity", "payload"}, &iteratorForAppendEventBatch{rows: arg})
}
