// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package egress

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TelemetryEvent struct {
	ID       int64
	At       pgtype.Timestamptz
	Source   string
	Kind     string
	Severity int32
	Payload  []byte
}
