// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package egress

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO telemetry_event (at, source, kind, severity, payload)
VALUES ($1, $2, $3, $4, $5)
`

type AppendEventParams struct {
	At       pgtype.Timestamptz
	Source   string
	Kind     string
	Severity int32
	Payload  []byte
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.Exec(ctx, appendEvent,
		arg.At,
		arg.Source,
		arg.Kind,
		arg.Severity,
		arg.Payload,
	)
	return err
}

type AppendEventBatchParams struct {
	At       pgtype.Timestamptz
	Source   string
	Kind     string
	Severity int32
	Payload  []byte
}
