// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Actuator struct {
	ID            string
	Name          string
	Enabled       bool
	States        string
	FailsafeState string
}

type AuditLog struct {
	ID     int64
	At     string
	Actor  string
	Action string
	Entity string
	Detail string
}

type EgressTarget struct {
	ID          string
	Name        string
	Enabled     bool
	Type        string
	Dsn         string
	WebhookUrl  string
	AuthToken   string
	MinSeverity int64
}

type ExternalSource struct {
	ID          string
	Name        string
	Enabled     bool
	Url         string
	AuthHeader  string
	AuthToken   string
	PollMs      int64
	Kind        string
	MaxAgeMs    int64
	MinValue    float64
	MaxValue    float64
	Disposition string
	FieldMap    string
}

type PolicyRule struct {
	ID              string
	Name            string
	Enabled         bool
	MatchKind       string
	MatchMinSev     int64
	MatchSourceID   string
	ActuatorID      string
	TargetState     string
	RequireOperator bool
	Priority        int64
}
