// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const countPendingAction = `-- name: CountPendingAction :one
SELECT COUNT(*) FROM queued_advisory
WHERE actuator_id = ? AND target_state = ? AND status = 'pending'
`

type CountPendingActionParams struct {
	ActuatorID  string
	TargetState string
}

func (q *Queries) CountPendingAction(ctx context.Context, arg CountPendingActionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingAction, arg.ActuatorID, arg.TargetState)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteActuator = `-- name: DeleteActuator :exec
DELETE FROM actuator WHERE id = ?
`

func (q *Queries) DeleteActuator(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteActuator, id)
	return err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM policy_rule WHERE id = ?
`

func (q *Queries) DeleteRule(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRule, id)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM external_source WHERE id = ?
`

func (q *Queries) DeleteSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSource, id)
	return err
}

const deleteTarget = `-- name: DeleteTarget :exec
DELETE FROM egress_target WHERE id = ?
`

func (q *Queries) DeleteTarget(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTarget, id)
	return err
}

const getPending = `-- name: GetPending :one
SELECT id, source_id, kind, severity, value, unit, observed_at, received_at, disposition, raw_json, actuator_id, target_state, rule_id, status, resolved_at, resolved_by
FROM queued_advisory WHERE id = ?
`

func (q *Queries) GetPending(ctx context.Context, id int64) (QueuedAdvisory, error) {
	row := q.db.QueryRowContext(ctx, getPending, id)
	var i QueuedAdvisory
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Kind,
		&i.Severity,
		&i.Value,
		&i.Unit,
		&i.ObservedAt,
		&i.ReceivedAt,
		&i.Disposition,
		&i.RawJson,
		&i.ActuatorID,
		&i.TargetState,
		&i.RuleID,
		&i.Status,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (at, actor, action, entity, detail)
VALUES (?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	At     string
	Actor  string
	Action string
	Entity string
	Detail string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.At,
		arg.Actor,
		arg.Action,
		arg.Entity,
		arg.Detail,
	)
	return err
}

const insertPending = `-- name: InsertPending :exec
INSERT INTO queued_advisory (source_id, kind, severity, value, unit, observed_at, received_at, disposition, raw_json, actuator_id, target_state, rule_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPendingParams struct {
	SourceID    string
	Kind        string
	Severity    int64
	Value       float64
	Unit        string
	ObservedAt  string
	ReceivedAt  string
	Disposition string
	RawJson     string
	ActuatorID  string
	TargetState string
	RuleID      string
}

func (q *Queries) InsertPending(ctx context.Context, arg InsertPendingParams) error {
	_, err := q.db.ExecContext(ctx, insertPending,
		arg.SourceID,
		arg.Kind,
		arg.Severity,
		arg.Value,
		arg.Unit,
		arg.ObservedAt,
		arg.ReceivedAt,
		arg.Disposition,
		arg.RawJson,
		arg.ActuatorID,
		arg.TargetState,
		arg.RuleID,
	)
	return err
}

const listActuators = `-- name: ListActuators :many
SELECT id, name, enabled, states, failsafe_state
FROM actuator ORDER BY id
`

func (q *Queries) ListActuators(ctx context.Context) ([]Actuator, error) {
	rows, err := q.db.QueryContext(ctx, listActuators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Actuator
	for rows.Next() {
		var i Actuator
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.States,
			&i.FailsafeState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudit = `-- name: ListAudit :many
SELECT id, at, actor, action, entity, detail
FROM audit_log ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListAudit(ctx context.Context, limit int64) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Actor,
			&i.Action,
			&i.Entity,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPending = `-- name: ListPending :many
SELECT id, source_id, kind, severity, value, unit, observed_at, received_at, disposition, raw_json, actuator_id, target_state, rule_id, status, resolved_at, resolved_by
FROM queued_advisory WHERE status = 'pending' ORDER BY id
`

func (q *Queries) ListPending(ctx context.Context) ([]QueuedAdvisory, error) {
	rows, err := q.db.QueryContext(ctx, listPending)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueuedAdvisory
	for rows.Next() {
		var i QueuedAdvisory
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Kind,
			&i.Severity,
			&i.Value,
			&i.Unit,
			&i.ObservedAt,
			&i.ReceivedAt,
			&i.Disposition,
			&i.RawJson,
			&i.ActuatorID,
			&i.TargetState,
			&i.RuleID,
			&i.Status,
			&i.ResolvedAt,
			&i.ResolvedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT id, name, enabled, match_kind, match_min_sev, match_source_id,
       actuator_id, target_state, disposition, priority
FROM policy_rule ORDER BY priority DESC, id
`

func (q *Queries) ListRules(ctx context.Context) ([]PolicyRule, error) {
	rows, err := q.db.QueryContext(ctx, listRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PolicyRule
	for rows.Next() {
		var i PolicyRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.MatchKind,
			&i.MatchMinSev,
			&i.MatchSourceID,
			&i.ActuatorID,
			&i.TargetState,
			&i.Disposition,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, name, enabled, url, auth_header, auth_token, poll_ms, kind, max_age_ms, min_value, max_value, field_map
FROM external_source ORDER BY id
`

func (q *Queries) ListSources(ctx context.Context) ([]ExternalSource, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalSource
	for rows.Next() {
		var i ExternalSource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Url,
			&i.AuthHeader,
			&i.AuthToken,
			&i.PollMs,
			&i.Kind,
			&i.MaxAgeMs,
			&i.MinValue,
			&i.MaxValue,
			&i.FieldMap,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargets = `-- name: ListTargets :many
SELECT id, name, enabled, type, dsn, webhook_url, auth_token, min_severity
FROM egress_target ORDER BY id
`

func (q *Queries) ListTargets(ctx context.Context) ([]EgressTarget, error) {
	rows, err := q.db.QueryContext(ctx, listTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EgressTarget
	for rows.Next() {
		var i EgressTarget
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Type,
			&i.Dsn,
			&i.WebhookUrl,
			&i.AuthToken,
			&i.MinSeverity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePending = `-- name: ResolvePending :execresult
UPDATE queued_advisory SET status = ?, resolved_at = ?, resolved_by = ?
WHERE id = ? AND status = 'pending'
`

type ResolvePendingParams struct {
	Status     string
	ResolvedAt string
	ResolvedBy string
	ID         int64
}

func (q *Queries) ResolvePending(ctx context.Context, arg ResolvePendingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, resolvePending,
		arg.Status,
		arg.ResolvedAt,
		arg.ResolvedBy,
		arg.ID,
	)
}

const upsertActuator = `-- name: UpsertActuator :exec
INSERT INTO actuator (id, name, enabled, states, failsafe_state)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  name=excluded.name, enabled=excluded.enabled,
  states=excluded.states, failsafe_state=excluded.failsafe_state
`

type UpsertActuatorParams struct {
	ID            string
	Name          string
	Enabled       bool
	States        string
	FailsafeState string
}

func (q *Queries) UpsertActuator(ctx context.Context, arg UpsertActuatorParams) error {
	_, err := q.db.ExecContext(ctx, upsertActuator,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.States,
		arg.FailsafeState,
	)
	return err
}

const upsertRule = `-- name: UpsertRule :exec
INSERT INTO policy_rule (id, name, enabled, match_kind, match_min_sev, match_source_id, actuator_id, target_state, disposition, priority)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  name=excluded.name, enabled=excluded.enabled, match_kind=excluded.match_kind,
  match_min_sev=excluded.match_min_sev, match_source_id=excluded.match_source_id,
  actuator_id=excluded.actuator_id, target_state=excluded.target_state,
  disposition=excluded.disposition, priority=excluded.priority
`

type UpsertRuleParams struct {
	ID            string
	Name          string
	Enabled       bool
	MatchKind     string
	MatchMinSev   int64
	MatchSourceID string
	ActuatorID    string
	TargetState   string
	Disposition   string
	Priority      int64
}

func (q *Queries) UpsertRule(ctx context.Context, arg UpsertRuleParams) error {
	_, err := q.db.ExecContext(ctx, upsertRule,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.MatchKind,
		arg.MatchMinSev,
		arg.MatchSourceID,
		arg.ActuatorID,
		arg.TargetState,
		arg.Disposition,
		arg.Priority,
	)
	return err
}

const upsertSource = `-- name: UpsertSource :exec
INSERT INTO external_source (id, name, enabled, url, auth_header, auth_token, poll_ms, kind, max_age_ms, min_value, max_value, field_map)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  name=excluded.name, enabled=excluded.enabled, url=excluded.url,
  auth_header=excluded.auth_header, auth_token=excluded.auth_token,
  poll_ms=excluded.poll_ms, kind=excluded.kind, max_age_ms=excluded.max_age_ms,
  min_value=excluded.min_value, max_value=excluded.max_value, field_map=excluded.field_map
`

type UpsertSourceParams struct {
	ID         string
	Name       string
	Enabled    bool
	Url        string
	AuthHeader string
	AuthToken  string
	PollMs     int64
	Kind       string
	MaxAgeMs   int64
	MinValue   float64
	MaxValue   float64
	FieldMap   string
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertSource,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Url,
		arg.AuthHeader,
		arg.AuthToken,
		arg.PollMs,
		arg.Kind,
		arg.MaxAgeMs,
		arg.MinValue,
		arg.MaxValue,
		arg.FieldMap,
	)
	return err
}

const upsertTarget = `-- name: UpsertTarget :exec
INSERT INTO egress_target (id, name, enabled, type, dsn, webhook_url, auth_token, min_severity)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  name=excluded.name, enabled=excluded.enabled, type=excluded.type,
  dsn=excluded.dsn, webhook_url=excluded.webhook_url,
  auth_token=excluded.auth_token, min_severity=excluded.min_severity
`

type UpsertTargetParams struct {
	ID          string
	Name        string
	Enabled     bool
	Type        string
	Dsn         string
	WebhookUrl  string
	AuthToken   string
	MinSeverity int64
}

func (q *Queries) UpsertTarget(ctx context.Context, arg UpsertTargetParams) error {
	_, err := q.db.ExecContext(ctx, upsertTarget,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Type,
		arg.Dsn,
		arg.WebhookUrl,
		arg.AuthToken,
		arg.MinSeverity,
	)
	return err
}
