// This file configures the SQLite database.
//
// The data base contains system configuration:
// - All the targets to push data to and pull data from and policies.
// - The actuator list for devices attached.
// - An audit log to track the changes made to the system over time.
//
// Only the local dashboard can write to the data base.

package store

import (
	"context"
	"database/sql"
	_ "embed"
	"fmt"
	"server/actuator"
	"server/advisory"
	"server/policy"

	_ "modernc.org/sqlite"
)

type Store struct {
	db      *sql.DB
	queries *Queries // Embedded queries struct autogenerated by sqlc
}

//go:embed schema.sql
var embeddedSchema string

type EgressType string

const (
	TypeSupabase EgressType = "supabase" // append to Postgres read-model
	TypeWebhook  EgressType = "webhook"  // POST to a central EWS authority
)

// Open initializes the SQLite database and sets up the sqlc query orchestrator
func Open(ctx context.Context, path string) (*Store, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, err
	}

	db.SetMaxOpenConns(1)

	s := &Store{
		db:      db,
		queries: New(db),
	}

	// This apply CREATE TABLE blocks.
	if err := s.migrate(ctx); err != nil {
		return nil, err
	}

	return s, nil
}

func (s *Store) migrate(ctx context.Context) error {
	if _, err := s.db.ExecContext(ctx, embeddedSchema); err != nil {
		return fmt.Errorf("failed to execute runtime schema migration: %w", err)
	}
	return nil
}

// Shuts down the underlying pool
func (s *Store) Close() error {
	if s.db != nil {
		return s.db.Close()
	}
	return nil
}

// Validate we have all the data we need for EgressTarget
func validateTarget(t EgressTarget) error {
	if t.ID == "" {
		return fmt.Errorf("target: id required")
	}
	switch EgressType(t.Type) {
	case TypeSupabase:
		if t.Dsn == "" {
			return fmt.Errorf("target %s: supabase target needs a DSN", t.ID)
		}
	case TypeWebhook:
		if t.WebhookUrl == "" {
			return fmt.Errorf("target %s: webhook target needs a URL", t.ID)
		}
	default:
		return fmt.Errorf("target %s: unknown type %q", t.ID, t.Type)
	}
	return nil
}

// Validate we have all the data we need for an ExternalSource.
func validateSource(e ExternalSource) error {
	if e.ID == "" || e.Url == "" {
		return fmt.Errorf("source: id and url are required")
	}

	if e.PollMs < 1000 {
		return fmt.Errorf("source %s: poll_interval too small (min 1s)", e.ID)
	}

	if e.MaxValue != 0 && e.MinValue > e.MaxValue {
		return fmt.Errorf("source %s: min_value > max_value", e.ID)
	}
	return nil
}

// Validate we have all the required data for a rule.
func validateRule(r policy.Rule) error {
	if r.ID == "" || r.ActuatorID == "" || r.TargetState == "" {
		return fmt.Errorf("rule: id, actuator_id, target_state required")
	}

	if !advisory.Disposition(r.Disposition).Valid() {
		return fmt.Errorf("source %s: invalid disposition %q", r.ID, r.Disposition)
	}
	return nil
}

// Validate we have all the required data for an actuator.
func validateActuator(a actuator.Spec) error {
	if a.ID == "" || len(a.States) == 0 {
		return fmt.Errorf("actuator: id and at least one state required")
	}
	for _, s := range a.States {
		if s == a.FailsafeState {
			return nil
		}
	}
	return fmt.Errorf("actuator %s: failsafe_state %q not in states", a.ID, a.FailsafeState)
}
